---
language: python
python: "2.7"

env:
  - SITE=playbook.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl -y

install:
  - pip install -U ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "ansible-playbook -i ci/inventory ci/$SITE --syntax-check"

  - "ansible-playbook -i ci/inventory ci/playbook.yml --connection=local --sudo -vvvv"

  - "node --version"